name: Recipe App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run backend tests
      run: |
        cd backend
        npm test
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm test
    
    - name: Authenticate to Google Cloud
      if: success()
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Set up Google Cloud CLI
      if: success()
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Configure Docker for Google Cloud
      if: success()
      run: |
        gcloud auth configure-docker
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
    
    - name: Build and push backend image
      if: success()
      run: |
        cd backend
        REPO_NAME=$(echo "${{ secrets.ARTIFACT_REPO_NAME }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}/backend:${{ github.sha }} .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}/backend:${{ github.sha }}
    
    - name: Build and push frontend image
      if: success()
      run: |
        cd frontend
        REPO_NAME=$(echo "${{ secrets.ARTIFACT_REPO_NAME }}" | tr '[:upper:]' '[:lower:]')
        # Get the backend URL for the frontend build
        BACKEND_URL=$(gcloud run services describe recipe-backend --region=${{ secrets.GCP_REGION }} --format='value(status.url)' 2>/dev/null || echo "https://recipe-backend-placeholder.run.app")
        docker build --build-arg VITE_API_URL=$BACKEND_URL -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}/frontend:${{ github.sha }} .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}/frontend:${{ github.sha }}
    
    - name: Deploy backend to Cloud Run
      if: success()
      run: |
        REPO_NAME=$(echo "${{ secrets.ARTIFACT_REPO_NAME }}" | tr '[:upper:]' '[:lower:]')
        gcloud run deploy recipe-backend \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}/backend:${{ github.sha }} \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 5000 \
          --memory 512Mi \
          --cpu 1
    
    - name: Deploy frontend to Cloud Run
      if: success()
      run: |
        REPO_NAME=$(echo "${{ secrets.ARTIFACT_REPO_NAME }}" | tr '[:upper:]' '[:lower:]')
        gcloud run deploy recipe-frontend \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}/frontend:${{ github.sha }} \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 80 \
          --memory 512Mi \
          --cpu 1
    
    - name: Get deployed URLs
      if: success()
      run: |
        echo "Backend URL: $(gcloud run services describe recipe-backend --region=${{ secrets.GCP_REGION }} --format='value(status.url)')"
        echo "Frontend URL: $(gcloud run services describe recipe-frontend --region=${{ secrets.GCP_REGION }} --format='value(status.url)')"